services:
  db:
    image: postgres:alpine
    container_name: jobs_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - jobs_db_posrgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer:latest
    container_name: jobs_db_manager
    restart: always
    ports:
      - "8000:8080"
    depends_on:
      - db

volumes:
  jobs_db_posrgres_data:
